# Seguimos trabajando con NumPy, en este caso practicaremos como acceder a distintos elementos de nuestros arrays y como cambiar su forma para poder hacer operaciones entre varios arrays.
    1. Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:


In [2]:
import numpy as np

In [12]:
array1 = np.random.random_sample((5,3))
array1

array([[0.17564554, 0.72029644, 0.45799372],
       [0.9279626 , 0.85483293, 0.39729669],
       [0.25231247, 0.13288668, 0.27450627],
       [0.36086191, 0.48353721, 0.54335961],
       [0.7539617 , 0.2008151 , 0.68936149]])

        1. El valor de la primera fila y la segunda columna.


In [13]:
array1[0,1]

0.7202964374930886

        2. Los valores de la segunda fila y las dos primeras columnas.


In [14]:
array1[1, :2]

array([0.9279626 , 0.85483293])

        3. Extraed las filas pares (incluyendo la 0) y todas las columnas.


In [15]:
array1[::2]

array([[0.17564554, 0.72029644, 0.45799372],
       [0.25231247, 0.13288668, 0.27450627],
       [0.7539617 , 0.2008151 , 0.68936149]])

        4.  Extraed los valores que sean mayores que 0.5.


In [16]:
array1[array1 > 0.5]

array([0.72029644, 0.9279626 , 0.85483293, 0.54335961, 0.7539617 ,
       0.68936149])

        5. Extraed los valores menores que 0.2 o mayores que 0.5


In [17]:
array1[(array1 > 0.5) | (array1 < 0.2)]

array([0.17564554, 0.72029644, 0.9279626 , 0.85483293, 0.13288668,
       0.54335961, 0.7539617 , 0.68936149])

    2. Cread dos array de tres dimensiones:
        1. El primero de 2 matrices, 5 filas y 3 columnas.


In [21]:
array2 = np.random.randint(1,50, (2,5,3))
array3 = np.random.randint(1,50, (3,2,5))
array2

array([[[21,  4, 24],
        [21,  4, 48],
        [37, 14, 25],
        [47,  5, 27],
        [21, 18, 26]],

       [[ 4, 48, 47],
        [16, 41, 36],
        [37, 36,  7],
        [19,  5, 21],
        [44, 25, 14]]])

In [22]:
array3

array([[[19,  6, 14, 47,  5],
        [31, 16, 42, 20, 28]],

       [[36, 40, 13, 34, 13],
        [ 1,  9, 33, 32, 19]],

       [[28, 14, 47, 47, 20],
        [ 7, 33, 32, 16, 29]]])

        2. El segundo de 3 matrices, 2 filas y 5 columnas


        3. Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.


In [23]:
def propiedades(parametro):
    print(parametro.shape)
    print(parametro.size)
    print(parametro.ndim)
    print(parametro.dtype)

In [24]:
propiedades(array2)

(2, 5, 3)
30
3
int64


In [25]:
propiedades(array3)

(3, 2, 5)
30
3
int64


        4. Sumad los dos arrays. ¿Podéis? ¿Por qué?


In [26]:
array4 = np.add(array2, array3)

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

No se puede porque tienen diferente forma.

        5. Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
            1. .reshape()
            2. .transpose()
             estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [29]:
array5 = np.reshape(array2, (3,2,5))

In [30]:
array5

array([[[21,  4, 24, 21,  4],
        [48, 37, 14, 25, 47]],

       [[ 5, 27, 21, 18, 26],
        [ 4, 48, 47, 16, 41]],

       [[36, 37, 36,  7, 19],
        [ 5, 21, 44, 25, 14]]])

In [33]:
array6 = np.transpose(array2, (2,0,1))

In [32]:
propiedades(array3)

(3, 2, 5)
30
3
int64


In [34]:
propiedades(array6)

(3, 2, 5)
30
3
int64


In [36]:
array8 = np.add(array6, array3)
array8

array([[[40, 27, 51, 94, 26],
        [35, 32, 79, 39, 72]],

       [[40, 44, 27, 39, 31],
        [49, 50, 69, 37, 44]],

       [[52, 62, 72, 74, 46],
        [54, 69, 39, 37, 43]]])