    1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?


In [45]:
import numpy as np

In [46]:
np.random.seed(1)

In [47]:
np.random.seed(1)
array5 = np.random.random_sample((3,5))
array5

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02]])

In [48]:
np.random.seed(1)
array6 = np.random.random_sample((3,5))
array6

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02]])

    2. Cread los siguientes arrays:
        2.1.   Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.
        2.2. Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.


In [49]:
array3 = np.round(np.random.uniform(0,10, (2,3,5)), 0)
array3

array([[[ 7.,  4.,  6.,  1.,  2.],
        [ 8., 10.,  3.,  7.,  9.],
        [ 9.,  1.,  0.,  2.,  9.]],

       [[ 1.,  4., 10.,  5.,  7.],
        [ 3.,  7.,  8.,  0.,  8.],
        [10.,  7.,  3.,  8.,  1.]]])

In [50]:
array3_unicos = np.unique(array3)
array3_unicos


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [51]:
array4= np.random.binomial(10, 0.3, size = (2,3,5))
array4

array([[[3, 5, 2, 2, 1],
        [0, 4, 2, 2, 3],
        [1, 3, 1, 3, 4]],

       [[1, 3, 4, 3, 1],
        [3, 4, 3, 5, 3],
        [5, 1, 1, 4, 3]]])

In [52]:
array4_unicos = np.unique(array4)
array4_unicos

array([0, 1, 2, 3, 4, 5])

    3. En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
        3.1. Elementos comunes entre los dos arrays


In [53]:
np.intersect1d(array3_unicos, array4_unicos)

array([0., 1., 2., 3., 4., 5.])

Nos da los elementos comunos de los dos arrays. Al ser uno tipo float, el resultado sera de tipo float.

        3.2. Unión de los dos arrays


In [54]:
np.union1d(array3_unicos, array4_unicos)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Nos une los dos arrays quitando los repetidos. Al ser uno tipo float, el resultado sera de tipo float.

        3.3. ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos
⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?


In [55]:
np.setdiff1d(array3, array4_unicos)

array([ 6.,  7.,  8.,  9., 10.])

Nos da los elementos quel primer array que no estan en el segundo. Al ser uno tipo float, el resultado sera de tipo float.


    4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.
        4.1. Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.


In [123]:
array1 = np.random.randint(1,100, (80))
array2 = np.random.randint(1,100, (80))
array1

array([26, 56, 70,  6, 15, 88,  3, 92, 65, 99, 88, 59, 25, 46, 15, 78, 87,
       33, 92, 73, 39, 84, 21, 25, 72, 28, 38, 96, 83, 17, 55, 97, 53, 74,
        6, 67, 81, 95, 51,  3, 90, 33,  8, 90, 86, 37, 67, 74, 12, 36, 43,
       40, 53, 94, 85, 21, 74,  8, 53, 70, 58, 63, 90, 84, 17, 29, 46, 83,
       82, 69, 68, 62, 84, 70, 39, 75, 64, 73, 13, 35])

In [124]:
array2

array([25, 84, 35, 23, 90, 41, 88, 76, 78, 39, 76, 22, 16, 56, 69, 83, 69,
       12, 37, 58, 28, 80,  2, 13,  2,  9, 90, 64, 91, 16, 86, 81, 85, 28,
       94,  8, 15, 76, 13, 62, 21, 38, 63, 67, 34, 58, 75, 73,  6,  1,  3,
        5, 65, 58, 36, 31,  5, 76, 81, 15,  3, 53, 55, 16, 97, 89,  1, 60,
       63,  2, 92, 68, 82, 42, 84, 45, 98,  7, 88, 57])

        4.2. Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.


In [143]:
array11 = np.setxor1d(array1, array2)
len(array11)

36

In [125]:
array3 = np.setdiff1d(array1, array2)
len(array3)

16

In [137]:
array1_repes = np.unique(array1)
len(array1_repes)

55

In [138]:
array2_repes = np.unique(array2)
len(array2_repes)

59

In [140]:
array10 = np.intersect1d(array1_repes, array2_repes)
len(array10)

39

        4.3. Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.


In [126]:
array4 = np.setdiff1d(array2, array1)
len(array4)

20

        4.4. Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.


In [127]:
array5 = np.intersect1d(array1, array2)
len(array5)

39

        4.5. ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.


La diferencia de los dos arrays mas los valores unicos de cada uno suman casi el total, ya que faltan los elementos repetidos.