#El objetivo de la clase de hoy será crear unos cuántos DataFrames y Series a través de los siguientes ejercicios:

    1. ¿Qué diferencia hay entre una Serie y un DataFrame?


Una serie es un Dataframe de una columna y un Dataframe de una columna es una Serie.

In [1]:
import pandas as pd
import numpy as np

    2. Momento de trabajar con Series. Contestad a las siguientes preguntas:
        1. Crea dos listas:
            1. Una que se llame "valores" que tenga 7 números aleatorios.
            2. Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.


In [2]:
valores = np.random.randint(0, 20, (7))
print(valores)

[15  4  1 18  5 11  9]


In [3]:
indices = ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"]
indices

['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']

        2. A partir de estas dos listas cread una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.


In [4]:
serie1 = pd.Series(valores, index= indices)
serie1

lunes        15
martes        4
miercoles     1
jueves       18
viernes       5
sabado       11
domingo       9
dtype: int64

        3. A partir de las dos listas anteriores cread un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.


In [13]:
diccionario1 = {}
variable1 = zip(indices, valores)

for x,y in variable1:
    diccionario1.update({x:y})
print(diccionario1)

{'lunes': 15, 'martes': 4, 'miercoles': 1, 'jueves': 18, 'viernes': 5, 'sabado': 11, 'domingo': 9}


In [15]:
diccionario1

{'lunes': 15,
 'martes': 4,
 'miercoles': 1,
 'jueves': 18,
 'viernes': 5,
 'sabado': 11,
 'domingo': 9}

        4. Crea una Serie con el diccionario creado en el punto anterior.


In [16]:
serie2 = pd.Series(diccionario1)
serie2

lunes        15
martes        4
miercoles     1
jueves       18
viernes       5
sabado       11
domingo       9
dtype: int64

        5. ¿Qué forma tiene esta última Serie?


In [17]:
serie2.shape

(7,)

        6. ¿Qué tipo de datos tiene?


In [18]:
serie2.dtype

dtype('int64')

        7. ¿Qué tamaño tiene?


In [19]:
serie2.size

7

        8. ¿Cuáles son los índices de la Serie?


In [20]:
serie2.index

Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')

        9. ¿Y los values?


In [21]:
serie2.values

array([15,  4,  1, 18,  5, 11,  9])

        10. Extraed el valor para el índice "lunes"


In [22]:
serie2["lunes"]

15

        11. Extraed el valor para el índice "lunes", "martes" y "miércoles".


In [23]:
serie2["lunes":"miercoles"]

lunes        15
martes        4
miercoles     1
dtype: int64

        12. Extraed el valor para el índice "lunes" y "domingo".


In [25]:
serie2[["lunes", "domingo"]]

lunes      15
domingo     9
dtype: int64

    3. Es el turno de los DataFrames
        1. Cread un array de dos dimensiones con 4 filas y 3 columnas.


In [26]:
array1 = np.random.randint(0,20, (4,3))
array1

array([[ 3, 15, 18],
       [ 9,  6,  1],
       [ 3,  5, 10],
       [ 9,  3,  1]])

        2. Convertid el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".


In [27]:
paises = pd.DataFrame(array1, columns = ["españa", "francia", "italia"])

In [28]:
paises

españa  francia  italia
0       3       15      18
1       9        6       1
2       3        5      10
3       9        3       1

        3. Descargad el archivo "medallas" y cargad el DataFrame con la siguiente línea de código:
                df = pd.read_csv("medallas.csv", index_col=["País"])
                📌 NOTA Para evitar problemas guardar el archivo medallas.csv a la misma altura (en la misma carpeta) que el jupyter donde estamos trabajando.


In [29]:
df = pd.read_csv("medallas.csv", index_col=["País"])

        4. Usando el loc extraed todas las columnas de la fila de Tailandia.


In [30]:
df

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [31]:
df.loc[["Tailandia"]]

Unnamed: 0  Oro  Plata  Bronce
País                                     
Tailandia           7  132    175     278

        5. Usando el loc extraed todas las columnas de China e Irán.


In [32]:
df.loc[["China", "Irán"]]

Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

        6. Usando el loc extraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.


In [33]:
df.loc[["China", "Irán"], ["Oro", "Plata", "Bronce"]]

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

In [34]:
df

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

        7. Usando el iloc extraed la información de la India. Devolved todas las columnas.


In [35]:
df.iloc[[5]]

Unnamed: 0  Oro  Plata  Bronce
País                                 
India           6  154    202     315

        8. Usando el iloc extraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.


In [36]:
df.iloc[1:10:2]

Unnamed: 0   Oro  Plata  Bronce
País                                            
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235

        9. Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce".


In [37]:
df.iloc[1:10:2, 1:4]

Oro  Plata  Bronce
País                                
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

        10. Contestad a las siguientes preguntas:
            1. ¿Qué país consiguió más de 200 medallas de oro?


In [38]:
df[df.Oro > 200]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

            2. ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?


In [39]:
df[(df.Oro > 200)&(df.Plata > 1000)]

Unnamed: 0   Oro  Plata  Bronce
País                                  
Japón           2  1032   1037     985

            3. ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?


In [42]:
df[(df.Oro > 200)|(df.Bronce > 700)]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

        11. Como vemos hay una columna que se llama Unnamed: 0 que no nos interesa. Eliminad esa columna.


In [46]:
df = df.drop(["Unnamed: 0"],axis= 1)

        12. Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [51]:
df["Total"] = df.Oro + df.Plata + df.Bronce

In [54]:
df

Oro  Plata  Bronce  Total
País                                       
China            1473    994     720   3187
Japón            1032   1037     985   3054
Corea del Sur     745    663     827   2235
Irán              179    181     197    557
Kazajistán        155    158     224    537
India             154    202     315    671
Tailandia         132    175     278    585
Indonesia         112    131     240    483
China Taipéi       99    144     276    519
Corea del Norte    91    120     235    446