# En el ejercicio de hoy vamos a empezar a trabajar con NumPy. El objetivo de estos ejericicios es que creeis una serie de arrays, y hagáis una serie de operaciones matemáticas con ellos.
## 1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.
📌 Nota
- El array de 2 dimensiones debe ser de 2 filas y 3 columnas
- El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas


In [2]:
import numpy as np

In [11]:
array1 = np.random.rand(3) ## una dimension
array1

array([0.75317052, 0.29499343, 0.24749643])

In [12]:
array1.ndim

1

In [13]:
array2 = np.random.randint(0,10, (2,3))  ## dos dimensiones
array2

array([[3, 7, 4],
       [0, 6, 7]])

In [17]:
array3 = np.random.random_sample((2,3,5))  ## tres dimensiones
array3

array([[[0.83468534, 0.52246004, 0.1551334 , 0.6700466 , 0.20334615],
        [0.85232486, 0.48420393, 0.42154951, 0.58251219, 0.88429052],
        [0.87067504, 0.28903165, 0.08796209, 0.27581987, 0.90529204]],

       [[0.83534378, 0.72733253, 0.79034488, 0.89225171, 0.76180006],
        [0.09526588, 0.39257668, 0.37658481, 0.10099676, 0.40292845],
        [0.46401388, 0.88777016, 0.75739851, 0.69220485, 0.66440446]]])

In [16]:
array3.ndim

3

## 2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.


In [39]:
def propiedades(parametro):
    print(parametro.shape)
    print(parametro.size)
    print(parametro.ndim)
    print(parametro.dtype)
       

In [40]:
uno = propiedades(array1)
uno

(3,)
3
1
float64


In [41]:
dos = propiedades(array2)

(2, 3)
6
2
int64


In [42]:
tres = propiedades(array3)

(2, 3, 5)
30
3
float64


## 3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas


In [44]:
array4 = np.eye(3,3)
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
array5 = np.identity(3)
array5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.


In [57]:
identity_unos = np.ones_like(array3)
identity_unos

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

## 5. Es el momento de hacer algunas operaciones entre arrays
    1. ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

In [58]:
suma1 = np.add(array2, identity_unos)

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,5) 

Resultado ejercicio 1: no se pueden sumar porque tienen dimensiones diferentes.

    2. En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

In [54]:
array7 = np.random.random_sample((2,3,5))
array7

array([[[0.24016751, 0.54938233, 0.53669058, 0.84370045, 0.78580387],
        [0.90739355, 0.20716197, 0.92557827, 0.12610793, 0.59952079],
        [0.25357591, 0.57454642, 0.88624115, 0.70230502, 0.15884436]],

       [[0.98328521, 0.28133376, 0.78422438, 0.70242359, 0.55800724],
        [0.17979437, 0.1875222 , 0.77120391, 0.08032794, 0.1824301 ],
        [0.16897845, 0.16406256, 0.21242432, 0.92089555, 0.57149618]]])

In [59]:
suma2 = np.add(array7, identity_unos)
suma2

array([[[1.24016751, 1.54938233, 1.53669058, 1.84370045, 1.78580387],
        [1.90739355, 1.20716197, 1.92557827, 1.12610793, 1.59952079],
        [1.25357591, 1.57454642, 1.88624115, 1.70230502, 1.15884436]],

       [[1.98328521, 1.28133376, 1.78422438, 1.70242359, 1.55800724],
        [1.17979437, 1.1875222 , 1.77120391, 1.08032794, 1.1824301 ],
        [1.16897845, 1.16406256, 1.21242432, 1.92089555, 1.57149618]]])

    3. Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

In [60]:
producto1 = np.multiply(array7, identity_unos)
producto1

array([[[0.24016751, 0.54938233, 0.53669058, 0.84370045, 0.78580387],
        [0.90739355, 0.20716197, 0.92557827, 0.12610793, 0.59952079],
        [0.25357591, 0.57454642, 0.88624115, 0.70230502, 0.15884436]],

       [[0.98328521, 0.28133376, 0.78422438, 0.70242359, 0.55800724],
        [0.17979437, 0.1875222 , 0.77120391, 0.08032794, 0.1824301 ],
        [0.16897845, 0.16406256, 0.21242432, 0.92089555, 0.57149618]]])

In [61]:
producto2 = print(array7 * identity_unos)
producto2

[[[0.24016751 0.54938233 0.53669058 0.84370045 0.78580387]
  [0.90739355 0.20716197 0.92557827 0.12610793 0.59952079]
  [0.25357591 0.57454642 0.88624115 0.70230502 0.15884436]]

 [[0.98328521 0.28133376 0.78422438 0.70242359 0.55800724]
  [0.17979437 0.1875222  0.77120391 0.08032794 0.1824301 ]
  [0.16897845 0.16406256 0.21242432 0.92089555 0.57149618]]]


    4. Dividid las dos matrices

In [65]:
division1 = np.divide(array7, identity_unos)
division1


array([[[0.24016751, 0.54938233, 0.53669058, 0.84370045, 0.78580387],
        [0.90739355, 0.20716197, 0.92557827, 0.12610793, 0.59952079],
        [0.25357591, 0.57454642, 0.88624115, 0.70230502, 0.15884436]],

       [[0.98328521, 0.28133376, 0.78422438, 0.70242359, 0.55800724],
        [0.17979437, 0.1875222 , 0.77120391, 0.08032794, 0.1824301 ],
        [0.16897845, 0.16406256, 0.21242432, 0.92089555, 0.57149618]]])

In [66]:
division2 = print(identity_unos/array7)

[[[ 4.16376057  1.82022601  1.86327099  1.18525479  1.27258217]
  [ 1.10205765  4.82714075  1.08040566  7.92971563  1.66799887]
  [ 3.94359234  1.74050341  1.12836106  1.42388274  6.29547066]]

 [[ 1.01699892  3.55449701  1.27514526  1.4236424   1.79209143]
  [ 5.56190956  5.33270198  1.29667392 12.44896912  5.48155164]
  [ 5.9179144   6.09523585  4.70755901  1.08589948  1.74979297]]]
