En esta lección hemps aprendido algunas de las operaciones matemáticas más importantes que podemos aplicar a un array. Hoy pondremos en práctica algunas de estas operaciones, además de recordar algunas de los métodos aprendidos en otras lecciones y recordar como podemos iterar por un array.

1. Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:

In [1]:
import numpy as np

In [11]:
array = np.round(np.random.random_sample((2,3,5)), 1)
array

array([[[0.7, 0.2, 0.8, 0. , 1. ],
        [0.2, 0.3, 0.8, 0.3, 0.7],
        [1. , 0.3, 0.2, 0. , 0.6]],

       [[0.7, 0.5, 0.8, 0.7, 0.9],
        [0.5, 0.4, 0.8, 0.5, 0.9],
        [0.9, 0.2, 0.3, 0.8, 0.3]]])

2. Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [12]:
media_array = np.round(np.mean(array), 1)

media_array

0.5

3. Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [13]:
max_array = np.round(np.max(array), 1)
max_array

1.0

4. Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [14]:
min_array = np.round(np.min(array), 1)
min_array

0.0

5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E".

In [15]:
array

array([[[0.7, 0.2, 0.8, 0. , 1. ],
        [0.2, 0.3, 0.8, 0.3, 0.7],
        [1. , 0.3, 0.2, 0. , 0.6]],

       [[0.7, 0.5, 0.8, 0.7, 0.9],
        [0.5, 0.4, 0.8, 0.5, 0.9],
        [0.9, 0.2, 0.3, 0.8, 0.3]]])

In [16]:
array2 = np.empty_like(array, dtype= str)
array2

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [17]:
for i in range(0, array.shape[0]):
    for e in range(0, array.shape[1]):
        for elemento in range(0, array.shape[2]):
            if array[i][e][elemento] == media_array:
                array2[i][e][elemento] = "A"
            elif array[i][e][elemento] == max_array:
                array2[i][e][elemento] = "D"
            elif array[i][e][elemento] == min_array:
                array2[i][e][elemento] = "E"
            elif array[i][e][elemento] > media_array:
                array2[i][e][elemento] = "B"
            elif array[i][e][elemento] < media_array:
                array2[i][e][elemento] = "C"

print(array2)

[[['B' 'C' 'B' 'E' 'D']
  ['C' 'C' 'B' 'C' 'B']
  ['D' 'C' 'C' 'E' 'B']]

 [['B' 'A' 'B' 'B' 'B']
  ['A' 'C' 'B' 'A' 'B']
  ['B' 'C' 'C' 'B' 'C']]]


In [2]:
# a modo de ejemplo. Si tenemos el siguiente array
[[[0.4, 0.7, 0.2, 0.9, 0.2],
    [0.1, 0.9, 0.6, 0.1, 0.2],
    [1. , 0.2, 0.1, 0.8, 0.3]],

   [[0. , 0.3, 0.4, 0.5, 0.1],
    [0.5, 0.7, 0.9, 0. , 0.8],
    [0.5, 0.3, 0.5, 0.8, 0.1]]]

# sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

# nuestro array vacío debería quedar como este: 
[[["A", "B", "C", "B", "C"],
    ["C", "B", "B", "C", "C"],
    ["D" , "C", "C", "B", "C"]],

   [["E" , "C", "A", "B", "C"],
    ["B", "B","B", "E" , "B"],
    ["B", "C", "B", "B", "C"]]]

#💡 Pista 💡 Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales.

[[['A', 'B', 'C', 'B', 'C'],
  ['C', 'B', 'B', 'C', 'C'],
  ['D', 'C', 'C', 'B', 'C']],
 [['E', 'C', 'A', 'B', 'C'],
  ['B', 'B', 'B', 'E', 'B'],
  ['B', 'C', 'B', 'B', 'C']]]

6. Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.
En este caso:
Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.
Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [36]:
array_vacio = np.empty(30)
array_vacio

array([1. , 0.2, 1. , 0. , 1. , 0.2, 0.3, 1. , 0.3, 1. , 1. , 0.3, 0.2,
       0. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 0.4, 1. , 1. , 1. , 1. ,
       0.2, 0.3, 1. , 0.3])

In [20]:
array3 = array2.reshape(1,1,30)

In [21]:
array3

array([[['B', 'C', 'B', 'E', 'D', 'C', 'C', 'B', 'C', 'B', 'D', 'C',
         'C', 'E', 'B', 'B', 'A', 'B', 'B', 'B', 'A', 'C', 'B', 'A',
         'B', 'B', 'C', 'C', 'B', 'C']]], dtype='<U1')

In [24]:
array3.shape

(1, 1, 30)

In [31]:
array_vacio

2

In [46]:
for i in range(0, array3.shape[0]):
    for e in range(0, array3.shape[1]):
        for elemento in range(0, array3.shape[2]):
            if array3[i][e][elemento] == "A" or array3[i][e][elemento] == "B":
                array_vacio[elemento] = 1
            elif array3[i][e][elemento] == "C" or array3[i][e][elemento] == "D":
                array_vacio[elemento] = 2
            elif array3[i][e][elemento] == "E":
                array_vacio[elemento] = 3
for i in array_vacio:
    i = int(i)

# Cambiamos el tipo del array a int                
array_vacio.dtype = int

# Hacemos el reshape a 3 dimensiones

array_vacio = array_vacio.reshape(2,3,5)

array_vacio

array([[[1, 2, 1, 3, 2],
        [2, 2, 1, 2, 1],
        [2, 2, 2, 3, 1]],

       [[1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1],
        [1, 2, 2, 1, 2]]])